### ISSUE TITLE
OMDbService was left with package visibility

### ISSUE THREAD

**Issue by obarro** [BrianOdisho/omdb#1]
the class OMDbService was left with package visibility instead of public.
So i guess the Class that creates an instance of OMDbService has to be in a package with the seame name:
package me.shib.java.lib.omdb.service;

**Comment by BrianOdisho** [comment]
There is no class named OMDbService and all of the classes are public.  Are you sure your looking at the correct repo/library?

**Comment by BrianOdisho** [comment]
After a quick look I discovered a library with a similar name that I believe you were referring to.
